using System;

namespace Coffer_Systems
{
    internal class Invoice
    {
        public string PassengerCNIC { get; internal set; }
        public string invno { get; internal set; }
        public string yq { get; internal set; }
        public string invdate { get; internal set; }
        public string invtype { get; internal set; }
        public string invtitle { get; internal set; }
        public string clientcode { get; internal set; }
        public string customer { get; internal set; }
        public string invremarks { get; internal set; }
        public string etkt { get; internal set; }
        public string conj { get; internal set; }
        public string lastticket { get; internal set; }
        public string airline { get; internal set; }
        public string ticketpurchasefrom { get; internal set; }
        public string tickettype { get; internal set; }
        public string bsp { get; internal set; }
        public string xo { get; internal set; }
        public string postingdate { get; internal set; }
        public string status { get; internal set; }
        public string passengername { get; internal set; }
        public string sector { get; internal set; }
        public string fare { get; internal set; }
        public string classification { get; internal set; }
        public string deptdate { get; internal set; }
        public string pnr { get; internal set; }
        public string route { get; internal set; }
        public string passentertype { get; internal set; }
        public string category { get; internal set; }
        public string mainseg { get; internal set; }
        public string subseg { get; internal set; }
        public string iata { get; internal set; }
        public string mkt { get; internal set; }
        public string other { get; internal set; }
        public string soto { get; internal set; }
        public string sp { get; internal set; }
        public string yd { get; internal set; }
        public string pk { get; internal set; }
        public string fed { get; internal set; }
        public string ced { get; internal set; }
        public string xz { get; internal set; }
        public string whairline { get; internal set; }
        public string whclient { get; internal set; }
        public string pb { get; internal set; }
        public string oth { get; internal set; }
        public string tax { get; internal set; }
        public string frtx { get; internal set; }
        public string whtfix { get; internal set; }
        public string comm { get; internal set; }
        public string comamt { get; internal set; }
        public string extra { get; internal set; }
        public string comadj { get; internal set; }
        public string tcom { get; internal set; }
        public string airlinepay { get; internal set; }
        public string servicech { get; internal set; }
        public string serviceamt { get; internal set; }
        public string gst { get; internal set; }
        public string gstpay { get; internal set; }
        public string ins { get; internal set; }
        public string transferac { get; internal set; }
        public string kbairline { get; internal set; }
        public string clientreceive { get; internal set; }
        public string profitloss { get; internal set; }
        public string kbcust { get; internal set; }
        public string commkb { get; internal set; }
        public string disc { get; internal set; }
        public string discamt { get; internal set; }
        public string discadj { get; internal set; }
        public string gds { get; internal set; }
        public string fc { get; internal set; }
        public string fcreceivable { get; internal set; }
        public string fcpayable { get; internal set; }
        public string airlinepayable { get; internal set; }
        public string receivableclient { get; internal set; }
        public string otherpayable { get; internal set; }
        public string profitlossamt { get; internal set; }
        public string ticketvalue { get; internal set; }
        public string passengertype { get; internal set; }
        public string credit { get; internal set; }
        public string balance { get; internal set; }
        public string rcptno { get; internal set; }
        public string refundno { get; internal set; }
        public string rfdtype { get; internal set; }
        public string stockdate { get; internal set; }
        public string salesperson { get; internal set; }
        public string calcom { get; internal set; }
        public string percentage { get; internal set; }
        public string agent { get; internal set; }
        public string conjtkt { get; internal set; }
        public string xono { get; internal set; }
        public string piatkt { get; internal set; }
        public string rfdclaim { get; internal set; }
        public string vlddate { get; internal set; }
        public string totalsp { get; internal set; }
        public string totalinc { get; internal set; }
        public string rfdpayment { get; internal set; }
        public string clientpay { get; internal set; }
        public string airlinerec { get; internal set; }
        public string cancelcharges { get; internal set; }
        public string saledate { get; internal set; }
        public string receivable { get; internal set; }
        public string srvccharges { get; internal set; }
        public string refunddate { get; internal set; }
        public string svc { get; internal set; }
        public string client { get; internal set; }
        public string coupenno { get; internal set; }
        public string ticketno { get; internal set; }
        public string payment { get; internal set; }
        public string id { get; internal set; }
        public string visa { get; internal set; }
        public string food { get; internal set; }
        public string ziarat { get; internal set; }
        public string transport { get; internal set; }
        public string accomodation2 { get; internal set; }
        public string accomodation1 { get; internal set; }
        public int offset { get; internal set; }
    }
}